### ISSUE TITLE
Отрефакторить MessageHandler.cs к хуям собачьим

### ISSUE THREAD

**Issue by Shifu462** [Shifu462/TelegramDating#63]
нихуя не понятно

https://github.com/Shifu462/TelegramDating/blob/master/TelegramDating/Bot/MessageHandler.cs

**Comment by veselv2010** [comment]
согласен

**Comment by Shifu462** [comment]
https://github.com/Shifu462/TelegramDating/commit/803497f9d36813ef448a428dd109be425853d755

**Comment by Shifu462** [comment]
https://github.com/Shifu462/TelegramDating/commit/803497f9d36813ef448a428dd109be425853d755
